/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/


// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: {
    default: "Hilary Tech",
    template: "%s | Hilary Tech", // Pour les titres dynamiques
  },
  description: "Solutions numériques innovantes pour booster vos performances.",
  keywords: ["Next.js", "SEO", "Développement web", "Hilary Tech"],
  openGraph: {
    title: "Hilary Tech",
    description: "Solutions numériques innovantes pour booster vos performances.",
    url: "https://Hilary-Tech.com",
    siteName: "Hilary Tech",
    images: [
      {
        url: "https://Hilary-Tech.com/HT.png",
        width: 1200,
        height: 630,
        alt: "Hilary Tech",
      },
    ],
    locale: "fr_FR",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <head>
        <link rel="shortcut icon" href="/images/HT.png" type="image/png" />

        {/* Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap"
          rel="stylesheet"
        />

        {/* Owl Carousel CSS */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        />

        {/* Font Awesome */}
        <link rel="stylesheet" href="/css/font-awesome.min.css" />

        {/* AOS CSS */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css" />

        {/* Custom CSS */}
        <link rel="stylesheet" href="/css/bootstrap.css" />
        <link rel="stylesheet" href="/css/responsive.css" />
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>
        {children}

        {/* jQuery + Bootstrap */}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>


      </body>
    </html>
  );
}

